In [12]:
# 필요한 module 불러오기

import numpy as np
import pandas as pd
# 학습데이터와 테스트데이터를 분리해야 한다. (7:3 혹은 8:2로 분리)
from sklearn.model_selection import train_test_split
# 정규화
from sklearn.preprocessing import MinMaxScaler
# 우리 데이터에는 결측치와 이상치가 없다.
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dense
from tensorflow.keras.optimizers import Adam
# 다중 분류를 하다보니, one-hot encoding 작업을 해야 한다.
import tensorflow as tf

In [13]:
# Raw Data Loading

df = pd.read_csv('./data/bmi.csv', skiprows=3)
display(df.head(), df.shape) # (20000, 3)

# 결측치, 이상치는 따로 없다.

label  height  weight
0      1     188      71
1      2     161      68
2      0     178      52
3      2     136      63
4      1     145      52

(20000, 3)

In [11]:
# 데이터 분리
# 학습데이터와 테스트데이터를 분리

x_data_train, x_data_test, t_data_train, t_data_test = \
train_test_split(df[['height', 'weight']].values,
                df['label'].values,
                test_size=0.3)
# 원래는 train_test_split() 안에는 2차원 ndarray가 들어와야 하는데, 알아서 데이터 추출해서 사용한다.
print(x_data_train, x_data_train.shape) # (14000, 2)
# 6000개는 테스트, 14000개는 트레이닝 용으로 분류

# 정규화
scaler = MinMaxScaler()
scaler.fit(x_data_train)

x_data_train_norm = scaler.transform(x_data_train)
x_data_test_norm = scaler.transform(x_data_test)
print(x_data_train_norm, x_data_train_norm.shape) # (14000, 2)

# One-Hot 처리를 해야 한다.
print(t_data_train) # 1차원 데이터
# one-hot으로 바꾸면 2차원 데이터로 변함
# depth는 class의 수 => 분류의 개수
t_data_train_onehot = tf.one_hot(t_data_train, depth=3).numpy()
t_data_test_onehot = tf.one_hot(t_data_test, depth=3).numpy()


[[123  42]
 [187  77]
 [149  39]
 ...
 [183  36]
 [133  70]
 [121  74]] (14000, 2)
[[0.0375     0.15555556]
 [0.8375     0.93333333]
 [0.3625     0.08888889]
 ...
 [0.7875     0.02222222]
 [0.1625     0.77777778]
 [0.0125     0.86666667]] (14000, 2)
[2 1 0 ... 0 2 2]


In [14]:
# Model
model = Sequential()

# Layer 추가
model.add(Flatten(input_shape=(2, )))
model.add(Dense(3, activation='softmax'))

# Model 설정
model.compile(optimizer=Adam(learning_rate=1e-4),
              loss='categorical_crossentropy',
             metrics=['accuracy'])

# Model 학습
model.fit(x_data_train_norm,
         t_data_train_onehot,
         epochs=500,
         validation_split=0.2,
         verbose=1)

# 출력
# Epoch 1/500
# 350/350 [==============================] - 1s 1ms/step - loss: 1.1418 - accuracy: 0.3264 - val_loss: 1.1291 - val_accuracy: 0.3671
# Epoch 500/500
# 350/350 [==============================] - 0s 1ms/step - loss: 0.2749 - accuracy: 0.9707 - val_loss: 0.2705 - val_accuracy: 0.9739
# <keras.callbacks.History at 0x1b64be4b4c0>

# loss, accuracy : 학습 데이터로 만든 결과물. 크게 중요치 않은 데이터.
# val_loss, val_accuracy : 중간중간 테스트데이터로 검증받은 확률. 이게 중요한 데이터다.
#     val_loss : loss니까 낮을 수록 좋은 결과
#     val_accuracy : 정확도. 높을 수록 좋다.

Epoch 1/500
350/350 [==============================] - 1s 1ms/step - loss: 1.1418 - accuracy: 0.3264 - val_loss: 1.1291 - val_accuracy: 0.3671
Epoch 2/500
350/350 [==============================] - 0s 954us/step - loss: 1.1179 - accuracy: 0.3878 - val_loss: 1.1075 - val_accuracy: 0.4232
Epoch 3/500
350/350 [==============================] - 0s 913us/step - loss: 1.0970 - accuracy: 0.4379 - val_loss: 1.0884 - val_accuracy: 0.4646
Epoch 4/500
350/350 [==============================] - 0s 956us/step - loss: 1.0785 - accuracy: 0.4777 - val_loss: 1.0713 - val_accuracy: 0.4996
Epoch 5/500
350/350 [==============================] - 0s 907us/step - loss: 1.0620 - accuracy: 0.5133 - val_loss: 1.0561 - val_accuracy: 0.5307
Epoch 6/500
350/350 [==============================] - 0s 945us/step - loss: 1.0471 - accuracy: 0.5416 - val_loss: 1.0423 - val_accuracy: 0.5536
Epoch 7/500
350/350 [==============================] - 0s 859us/step - loss: 1.0335 - accuracy: 0.5622 - val_loss: 1.0296 - val_accu

350/350 [==============================] - 0s 807us/step - loss: 0.7205 - accuracy: 0.7924 - val_loss: 0.7205 - val_accuracy: 0.7818
Epoch 58/500
350/350 [==============================] - 0s 883us/step - loss: 0.7165 - accuracy: 0.7934 - val_loss: 0.7165 - val_accuracy: 0.7829
Epoch 59/500
350/350 [==============================] - 0s 842us/step - loss: 0.7125 - accuracy: 0.7937 - val_loss: 0.7125 - val_accuracy: 0.7854
Epoch 60/500
350/350 [==============================] - 0s 821us/step - loss: 0.7086 - accuracy: 0.7971 - val_loss: 0.7086 - val_accuracy: 0.7868
Epoch 61/500
350/350 [==============================] - 0s 929us/step - loss: 0.7047 - accuracy: 0.7979 - val_loss: 0.7047 - val_accuracy: 0.7886
Epoch 62/500
350/350 [==============================] - 0s 869us/step - loss: 0.7009 - accuracy: 0.7981 - val_loss: 0.7008 - val_accuracy: 0.7907
Epoch 63/500
350/350 [==============================] - 0s 918us/step - loss: 0.6971 - accuracy: 0.7999 - val_loss: 0.6971 - val_accuracy

350/350 [==============================] - 0s 886us/step - loss: 0.5581 - accuracy: 0.8552 - val_loss: 0.5573 - val_accuracy: 0.8432
Epoch 114/500
350/350 [==============================] - 0s 852us/step - loss: 0.5560 - accuracy: 0.8554 - val_loss: 0.5552 - val_accuracy: 0.8436
Epoch 115/500
350/350 [==============================] - 0s 863us/step - loss: 0.5540 - accuracy: 0.8560 - val_loss: 0.5532 - val_accuracy: 0.8436
Epoch 116/500
350/350 [==============================] - 0s 920us/step - loss: 0.5519 - accuracy: 0.8561 - val_loss: 0.5511 - val_accuracy: 0.8439
Epoch 117/500
350/350 [==============================] - 0s 887us/step - loss: 0.5499 - accuracy: 0.8561 - val_loss: 0.5491 - val_accuracy: 0.8446
Epoch 118/500
350/350 [==============================] - 0s 939us/step - loss: 0.5480 - accuracy: 0.8569 - val_loss: 0.5471 - val_accuracy: 0.8450
Epoch 119/500
350/350 [==============================] - 0s 896us/step - loss: 0.5460 - accuracy: 0.8569 - val_loss: 0.5452 - val_ac

Epoch 169/500
350/350 [==============================] - 0s 900us/step - loss: 0.4674 - accuracy: 0.8871 - val_loss: 0.4658 - val_accuracy: 0.8850
Epoch 170/500
350/350 [==============================] - 0s 903us/step - loss: 0.4661 - accuracy: 0.8883 - val_loss: 0.4645 - val_accuracy: 0.8864
Epoch 171/500
350/350 [==============================] - 0s 922us/step - loss: 0.4648 - accuracy: 0.8889 - val_loss: 0.4632 - val_accuracy: 0.8882
Epoch 172/500
350/350 [==============================] - 0s 917us/step - loss: 0.4636 - accuracy: 0.8888 - val_loss: 0.4620 - val_accuracy: 0.8886
Epoch 173/500
350/350 [==============================] - 0s 946us/step - loss: 0.4623 - accuracy: 0.8900 - val_loss: 0.4607 - val_accuracy: 0.8893
Epoch 174/500
350/350 [==============================] - 0s 890us/step - loss: 0.4611 - accuracy: 0.8901 - val_loss: 0.4595 - val_accuracy: 0.8896
Epoch 175/500
350/350 [==============================] - 0s 929us/step - loss: 0.4599 - accuracy: 0.8902 - val_loss: 0

Epoch 225/500
350/350 [==============================] - 0s 934us/step - loss: 0.4083 - accuracy: 0.9154 - val_loss: 0.4059 - val_accuracy: 0.9157
Epoch 226/500
350/350 [==============================] - 0s 971us/step - loss: 0.4074 - accuracy: 0.9154 - val_loss: 0.4050 - val_accuracy: 0.9175
Epoch 227/500
350/350 [==============================] - 0s 1ms/step - loss: 0.4066 - accuracy: 0.9171 - val_loss: 0.4042 - val_accuracy: 0.9175
Epoch 228/500
350/350 [==============================] - 0s 962us/step - loss: 0.4057 - accuracy: 0.9171 - val_loss: 0.4033 - val_accuracy: 0.9175
Epoch 229/500
350/350 [==============================] - 0s 898us/step - loss: 0.4048 - accuracy: 0.9175 - val_loss: 0.4024 - val_accuracy: 0.9186
Epoch 230/500
350/350 [==============================] - 0s 887us/step - loss: 0.4040 - accuracy: 0.9181 - val_loss: 0.4016 - val_accuracy: 0.9182
Epoch 231/500
350/350 [==============================] - 0s 919us/step - loss: 0.4032 - accuracy: 0.9184 - val_loss: 0.4

Epoch 281/500
350/350 [==============================] - 0s 975us/step - loss: 0.3663 - accuracy: 0.9383 - val_loss: 0.3633 - val_accuracy: 0.9375
Epoch 282/500
350/350 [==============================] - 0s 930us/step - loss: 0.3657 - accuracy: 0.9385 - val_loss: 0.3627 - val_accuracy: 0.9375
Epoch 283/500
350/350 [==============================] - 0s 978us/step - loss: 0.3650 - accuracy: 0.9385 - val_loss: 0.3621 - val_accuracy: 0.9393
Epoch 284/500
350/350 [==============================] - 0s 947us/step - loss: 0.3644 - accuracy: 0.9384 - val_loss: 0.3614 - val_accuracy: 0.9393
Epoch 285/500
350/350 [==============================] - 0s 962us/step - loss: 0.3638 - accuracy: 0.9387 - val_loss: 0.3608 - val_accuracy: 0.9400
Epoch 286/500
350/350 [==============================] - 0s 999us/step - loss: 0.3632 - accuracy: 0.9388 - val_loss: 0.3601 - val_accuracy: 0.9400
Epoch 287/500
350/350 [==============================] - 0s 983us/step - loss: 0.3626 - accuracy: 0.9389 - val_loss: 0

Epoch 337/500
350/350 [==============================] - 0s 1ms/step - loss: 0.3348 - accuracy: 0.9525 - val_loss: 0.3314 - val_accuracy: 0.9532
Epoch 338/500
350/350 [==============================] - 0s 983us/step - loss: 0.3344 - accuracy: 0.9526 - val_loss: 0.3309 - val_accuracy: 0.9532
Epoch 339/500
350/350 [==============================] - 0s 927us/step - loss: 0.3339 - accuracy: 0.9528 - val_loss: 0.3304 - val_accuracy: 0.9532
Epoch 340/500
350/350 [==============================] - 0s 908us/step - loss: 0.3334 - accuracy: 0.9529 - val_loss: 0.3299 - val_accuracy: 0.9532
Epoch 341/500
350/350 [==============================] - 0s 948us/step - loss: 0.3329 - accuracy: 0.9531 - val_loss: 0.3294 - val_accuracy: 0.9536
Epoch 342/500
350/350 [==============================] - 0s 963us/step - loss: 0.3324 - accuracy: 0.9532 - val_loss: 0.3289 - val_accuracy: 0.9536
Epoch 343/500
350/350 [==============================] - 0s 968us/step - loss: 0.3319 - accuracy: 0.9536 - val_loss: 0.3

Epoch 393/500
350/350 [==============================] - 0s 1ms/step - loss: 0.3102 - accuracy: 0.9618 - val_loss: 0.3063 - val_accuracy: 0.9625
Epoch 394/500
350/350 [==============================] - 0s 997us/step - loss: 0.3098 - accuracy: 0.9620 - val_loss: 0.3059 - val_accuracy: 0.9625
Epoch 395/500
350/350 [==============================] - 0s 969us/step - loss: 0.3094 - accuracy: 0.9617 - val_loss: 0.3055 - val_accuracy: 0.9625
Epoch 396/500
350/350 [==============================] - 0s 1ms/step - loss: 0.3090 - accuracy: 0.9620 - val_loss: 0.3051 - val_accuracy: 0.9625
Epoch 397/500
350/350 [==============================] - 0s 929us/step - loss: 0.3086 - accuracy: 0.9621 - val_loss: 0.3047 - val_accuracy: 0.9625
Epoch 398/500
350/350 [==============================] - 0s 938us/step - loss: 0.3082 - accuracy: 0.9620 - val_loss: 0.3043 - val_accuracy: 0.9629
Epoch 399/500
350/350 [==============================] - 0s 955us/step - loss: 0.3079 - accuracy: 0.9621 - val_loss: 0.304

Epoch 449/500
350/350 [==============================] - 0s 924us/step - loss: 0.2901 - accuracy: 0.9671 - val_loss: 0.2860 - val_accuracy: 0.9696
Epoch 450/500
350/350 [==============================] - 0s 910us/step - loss: 0.2898 - accuracy: 0.9673 - val_loss: 0.2857 - val_accuracy: 0.9696
Epoch 451/500
350/350 [==============================] - 0s 1ms/step - loss: 0.2895 - accuracy: 0.9672 - val_loss: 0.2853 - val_accuracy: 0.9700
Epoch 452/500
350/350 [==============================] - 0s 936us/step - loss: 0.2892 - accuracy: 0.9673 - val_loss: 0.2850 - val_accuracy: 0.9700
Epoch 453/500
350/350 [==============================] - 0s 981us/step - loss: 0.2889 - accuracy: 0.9681 - val_loss: 0.2847 - val_accuracy: 0.9700
Epoch 454/500
350/350 [==============================] - 0s 956us/step - loss: 0.2885 - accuracy: 0.9672 - val_loss: 0.2844 - val_accuracy: 0.9714
Epoch 455/500
350/350 [==============================] - 0s 1ms/step - loss: 0.2882 - accuracy: 0.9677 - val_loss: 0.284

In [16]:
# 모델의 evaluation(평가) 진행
model.evaluate(x_data_test_norm, t_data_test_onehot)
# 출력
#     188/188 [==============================] - 0s 633us/step - loss: 0.2742 - accuracy: 0.9707
#     [0.2741805911064148, 0.9706666469573975]
#     [최종 loss값, 최종 accuracy값]


188/188 [==============================] - 0s 707us/step - loss: 0.2742 - accuracy: 0.9707


[0.2741805911064148, 0.9706666469573975]

In [20]:
# 예측
predict_data = np.array([[180, 76]])
scaled_predict_data = scaler.transform(predict_data)
print(model.predict(scaled_predict_data))


1/1 [==============================] - 0s 16ms/step
[[0.02958116 0.6650098  0.30540907]]
