In [1]:
# 이제부터 Numpy에 대해서 알아보자.
# 여기서부터는 약간의 코드와 함께 이해를 동반해야 한다.

# 데이터 분석, 머신러닝, 딥러닝 이런 분야를 할 때
#     가장 시간이 많이 걸리고 잘 해야되는 것이 뭘까?
#     데이터 수집과 정제
#     우리가 얻을 수 있는 데이터는 쓸모없는 데이터들이 아주아주 많다.
#     거기서 쓸모없는 데이터들을 계속 제거하면서 정제해야한다.
# 딥러닝, 머신러닝만 중요한 게 아니다.
#     근데 이런 건 그냥 가져다 쓰면 쓸 수 있다.
#     사실 데이터 핸들링이 제일 중요하다.


In [2]:
# Numpy(Numerical Python)
#     수치와 관련된 계산
#     pandas(데이터 분석 module)와 matplotlib(시각화)의 base가 되는 기본 자료구조를 제공한다.
#     직접적으로 데이터를 핸들링하는 경우는 별로 없지만, 자료구조의 특징들은 알고 있어야 한다.

# ndarray
# numpy가 제공하는 유일한 자료구조
# n-dimensional array. n차원 배열. 다차원 배열
# 보다 적은 메모리를 필요로 하고, 훨씬 더 빠른 처리를 할 수 있다.

In [16]:
# numpy는 외부 module이기 때문에 당연히 설치해야 한다.
# numpy 설치 명령어
#     conda install numpy
# 외부 모듈을 파이썬에서 쓰기 위해서는 import 구문이 필요하다.
# import numpy
#     이렇게만 잡으면, 이름을 numpy 로 계속 사용해야 한다.
import numpy as np
#     aliasing을 잡자. 전세계가 이렇게 잡는다.

a = [1, 2, 3, 4, 5] # python의 list
print(a) # 출력 : [1, 2, 3, 4, 5]

# b = np.array() # numpyt에서 array를 생성한다.
b = np.array([1, 2, 3, 4, 5]) # 파이썬의 list를 가지고 numpy의 ndarray를 만들어준다.
print(b) # 출력 : [1 2 3 4 5]
#     리스트 출력과 ndarray의 출력은 다르다. 이번엔 콤마 가 없다.
print(type(b)) # 출력 : <class 'numpy.ndarray'>

# 기억해야하는 특징
# list 안에는 아무거나 막 들어올 수 있다.
c = [1, 3.14, '홍길동', True]
print(c) # 출력 : [1, 3.14, '홍길동', True]
# ndarray는 반드시 같은 데이터 타입끼리만 들어올 수 있다.
d = np.array([1, 2, 3.14, 4, 5])
print(d) # 출력 : [1.   2.   3.14 4.   5.  ]
print(d.dtype) # 출력 : float64


[1, 2, 3, 4, 5]
[1 2 3 4 5]
<class 'numpy.ndarray'>
[1, 3.14, '홍길동', True]
[1.   2.   3.14 4.   5.  ]
float64


In [21]:
# ndarray가 list와 가장 크게 차이나는 것
#     차원을 표현할 수 있다.
import numpy as np
#     윗쪽 cell에 이미 선언되어 있으므로 안 적어도 됨. 그냥 보기 좋게 적어두자.

# 중첩 리스트를 2차원 매트릭스로 변환하기
myList = [[1, 2, 3], [4, 5, 6]] # 중첩리스트
print(myList) # 출력 : [[1, 2, 3], [4, 5, 6]]
arr = np.array(myList)
print(arr) # 출력 : [[1 2 3] [4 5 6]]
print(arr[0, 1]) # 출력 : 2
#     0행 1열을 의미하는 numpy 출력법
print(arr[0])

[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]
2
[1 2 3]


In [26]:
# 중요한 속성이 있다.

# 1차원 ndarray를 하나 만들어보자.
arr = np.array([1, 2, 3, 4])
print(arr) # 출력 : [1 2 3 4]
# 속성 3가지
#     dtype : 데이터 타입
#     ndim : 차원
#     shape : 데이터의 형태. 차원의 수와 요소 수를 tuple로 같이 출력한다.
print(arr.dtype) # 출력 : int32
print(arr.ndim) # 출력 : 1
print(arr.shape) # 출력 : (4,)
#     tuple의 원소 개수 : 차원 수
#     tuple의 각 차원의 원소 값 : 요소 수

b = [[1, 2], [3, 4], [5, 6]]
arr = np.array(b)
print(arr.shape) # 출력 : (3, 2)
#     1차원:행. 2차원:열. 총 2개 차원이니까 tuple의 원소 수가 2개

[1 2 3 4]
int32
1
(4,)
(3, 2)
