In [1]:
# 이제부터 Numpy에 대해서 알아보자.
# 여기서부터는 약간의 코드와 함께 이해를 동반해야 한다.

# 데이터 분석, 머신러닝, 딥러닝 이런 분야를 할 때
#     가장 시간이 많이 걸리고 잘 해야되는 것이 뭘까?
#     데이터 수집과 정제
#     우리가 얻을 수 있는 데이터는 쓸모없는 데이터들이 아주아주 많다.
#     거기서 쓸모없는 데이터들을 계속 제거하면서 정제해야한다.
# 딥러닝, 머신러닝만 중요한 게 아니다.
#     근데 이런 건 그냥 가져다 쓰면 쓸 수 있다.
#     사실 데이터 핸들링이 제일 중요하다.


In [2]:
# Numpy(Numerical Python)
#     수치와 관련된 계산
#     pandas(데이터 분석 module)와 matplotlib(시각화)의 base가 되는 기본 자료구조를 제공한다.
#     직접적으로 데이터를 핸들링하는 경우는 별로 없지만, 자료구조의 특징들은 알고 있어야 한다.

# ndarray
# numpy가 제공하는 유일한 자료구조
# n-dimensional array. n차원 배열. 다차원 배열
# 보다 적은 메모리를 필요로 하고, 훨씬 더 빠른 처리를 할 수 있다.

In [16]:
# numpy는 외부 module이기 때문에 당연히 설치해야 한다.
# numpy 설치 명령어
#     conda install numpy
# 외부 모듈을 파이썬에서 쓰기 위해서는 import 구문이 필요하다.
# import numpy
#     이렇게만 잡으면, 이름을 numpy 로 계속 사용해야 한다.
import numpy as np
#     aliasing을 잡자. 전세계가 이렇게 잡는다.

a = [1, 2, 3, 4, 5] # python의 list
print(a) # 출력 : [1, 2, 3, 4, 5]

# b = np.array() # numpyt에서 array를 생성한다.
b = np.array([1, 2, 3, 4, 5]) # 파이썬의 list를 가지고 numpy의 ndarray를 만들어준다.
print(b) # 출력 : [1 2 3 4 5]
#     리스트 출력과 ndarray의 출력은 다르다. 이번엔 콤마 가 없다.
print(type(b)) # 출력 : <class 'numpy.ndarray'>

# 기억해야하는 특징
# list 안에는 아무거나 막 들어올 수 있다.
c = [1, 3.14, '홍길동', True]
print(c) # 출력 : [1, 3.14, '홍길동', True]
# ndarray는 반드시 같은 데이터 타입끼리만 들어올 수 있다.
d = np.array([1, 2, 3.14, 4, 5])
print(d) # 출력 : [1.   2.   3.14 4.   5.  ]
print(d.dtype) # 출력 : float64


[1, 2, 3, 4, 5]
[1 2 3 4 5]
<class 'numpy.ndarray'>
[1, 3.14, '홍길동', True]
[1.   2.   3.14 4.   5.  ]
float64


In [3]:
# ndarray가 list와 가장 크게 차이나는 것
#     차원을 표현할 수 있다.
import numpy as np
#     윗쪽 cell에 이미 선언되어 있으므로 안 적어도 됨. 그냥 보기 좋게 적어두자.

# 중첩 리스트를 2차원 매트릭스로 변환하기
myList = [[1, 2, 3], [4, 5, 6]] # 중첩리스트
print(myList) # 출력 : [[1, 2, 3], [4, 5, 6]]
arr = np.array(myList)
print(arr) # 출력 : [[1 2 3] [4 5 6]]
print(arr[0, 1]) # 출력 : 2
#     0행 1열을 의미하는 numpy 출력법
print(arr[0])

[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]
2
[1 2 3]


In [26]:
# 중요한 속성이 있다.

# 1차원 ndarray를 하나 만들어보자.
arr = np.array([1, 2, 3, 4])
print(arr) # 출력 : [1 2 3 4]
# 속성 3가지
#     dtype : 데이터 타입
#     ndim : 차원
#     shape : 데이터의 형태. 차원의 수와 요소 수를 tuple로 같이 출력한다.
print(arr.dtype) # 출력 : int32
print(arr.ndim) # 출력 : 1
print(arr.shape) # 출력 : (4,)
#     tuple의 원소 개수 : 차원 수
#     tuple의 각 차원의 원소 값 : 요소 수

b = [[1, 2], [3, 4], [5, 6]]
arr = np.array(b)
print(arr.shape) # 출력 : (3, 2)
#     1차원:행. 2차원:열. 총 2개 차원이니까 tuple의 원소 수가 2개

[1 2 3 4]
int32
1
(4,)
(3, 2)


In [7]:
# 데이터 표현

a = 10 # 0차원. scalar. 단순한 값 하나.
b = [10, 20, 30] # 1차원. vector. 정확히는 방향성이 있는 걸 벡터라고 부른다.
c = [[1, 2, 3], [4, 5, 6]] # 2차원. matrix. 행렬
d = [[[1, 2, 3, 4], [4, 5, 6, 7]], [[1, 2, 3, 4], [4, 5, 6, 7]]] # 3차원. 다차원배열

# numpy의 ndarray
arr = np.array(b) # 1차원(vector)
print(arr)
arr = np.array(c) # 2차원(matrix-행렬)
print(arr)
arr = np.array(d) # 3차원
print(arr)
print(arr.shape) # 출력 : (2, 2, 4)
#     요소가 3개 출력됐으니까 3차원

[10 20 30]
[[1 2 3]
 [4 5 6]]
[[[1 2 3 4]
  [4 5 6 7]]

 [[1 2 3 4]
  [4 5 6 7]]]
(2, 2, 4)


In [19]:
# ndarray를 만드는 가장 쉬운 방법
# np.array()를 이용해서 만들자.

# 색다르게 만드는 방법
# zeros(shape)
arr = np.zeros((3, 4))
print(arr) # 출력 : 3행 4열. 0이 총 12개

# arange()
#     파이썬의 range와 동일한 역할을 한다. 범위 내의 요소들을 일차원으로 나열해서 가지고 있다.
#     파이썬의 range와 차이점
#         파이썬의 range()는 단순한 개념일 뿐, 실제 데이터를 메모리에 가지고 있지 않다.
#         numpy의 arange()는 데이터를 실제로 가지고 있다.

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [21]:
arr = np.arange(0, 12, 1)
print(arr) # 출력 : [ 0  1  2  3  4  5  6  7  8  9 10 11]
#     1차원 ndarry

arr1 = arr.reshape(3, 4)
print(arr1)

arr[-1] = 100
print(arr)
print(arr1) # arr의 값을 바꿨는데 arr1의 값도 변한다.
#     이러한 성질을 view 라고 한다.
arr2 = arr.reshape(2, 2, 3)
print(arr2)

# reshape에서 -1의 의미
#     고정되지 않은 크기
arr1 = arr.reshape(-1, 2)
print(arr1) # 열의 크기가 2로 고정됨. 따라서 행의 크기가 6이 된다.
arr1 = arr.reshape(-1, 2, 2)
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[  0   1   2   3   4   5   6   7   8   9  10 100]
[[  0   1   2   3]
 [  4   5   6   7]
 [  8   9  10 100]]
[[[  0   1   2]
  [  3   4   5]]

 [[  6   7   8]
  [  9  10 100]]]
[[  0   1]
 [  2   3]
 [  4   5]
 [  6   7]
 [  8   9]
 [ 10 100]]
[[[  0   1]
  [  2   3]]

 [[  4   5]
  [  6   7]]

 [[  8   9]
  [ 10 100]]]


In [32]:
# numpy array도 indexing과 slicing을 할 수 있다.

arr = np.arange(0, 5, 1)
print(arr)
print(arr[-1]) # 출력 : 4

print(arr[0:2]) # 출력 : [0 1]
print(arr[2:-1]) # 출력 : [2, 3]. -1이면 마지막 4를 가리키고, 4는 exclusive니까 미출력
print(arr[0::2]) # 출력 : [0 2 4]. 맨 끝까지, 2칸씩 넘어간다.

arr = np.arange(1, 17, 1)
print(arr) # 1~16까지
arr = np.arange(1, 17, 1).reshape(4,4)
print(arr) # 1~16까지. 4행 4열
print(arr[1, 2]) # 출력 : 7. 2행 3열 요소 출력
print(arr[1, 2:4]) # 출력 : [7 8]. 2행 3~4열 요소 출력
print(arr[:, 2]) # 출력 : [ 3 7 11 15]. 모든 행, 3번째 열 출력

[0 1 2 3 4]
4
[0 1]
[2 3]
[0 2 4]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
7
[7 8]
[ 3  7 11 15]


In [43]:
# 기본 indexing과 slicing은 간단하다. python과 동일하다.
# indexing에는 특이한 indexing 기법이 두 개 더 있다.
# 기본 indexing, Boolean indexing, Fancy indexing

arr = np.arange(0, 5, 1)
print(arr)

# boolean mask 내가 적용하는 ndarray와 shape이 같아야 한다.
boolean_mask = np.array([1, 2, 3, 4, 5])
arr = np.arange(0, 5, 1)
print(arr)

boolean_mask = np.array([True, False, True, True, False])
print(arr[boolean_mask])


[0 1 2 3 4]
[0 1 2 3 4]
[0 2 3]


In [44]:
arr = np.array([1, 2, 3, 4, 5])
print(arr) # 출력 : [1 2 3 4 5]

arr1 = np.array([10, 20, 30, 40, 50])
print(arr1) # 출력 : [10 20 30 40 50]

print(arr + arr1) # 출력 : [11 22 33 44 55]
#     같은 위치의 데이터끼리 연산이 이루어진다.
#     이게 바로 ndarray를 사용하는 가장 큰 이유

arr = np.array([1, 2, 3, 4, 5])
arr1 = np.array([5, 4, 3, 2, 1])
print(arr > arr1) # 출력 : [False False False  True  True]


[1 2 3 4 5]
[10 20 30 40 50]
[11 22 33 44 55]
[False False False  True  True]


In [57]:
# 퀴즈. 코드 한 줄로 짝수만 출력하기
arr = np.arange(0, 10, 1)
print(arr)
# 정답
print(arr[arr % 2 ==0])

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [64]:
# 또 다른 indexing 방법 - Fancy Indexing

# copy()
#     view만 바꾸는 게 아니라, 실제로 결과물 그대로 메모리에 저장하는 것
arr = np.arange(0, 12, 1).reshape(3, 4).copy()
print(arr)

# slicing 결과물
print(arr[2, 2]) # 10. scalar
print(arr[1:2, 2]) # [6]. vector
#     slicing이 들어갔으니까 결과가 1차원으로 나온다.
print(arr[1:2, 1:2]) # [[5]]. matrix
#     행, 열 둘 다 slicing됐기 때문

# Fancy indexing
# 원하는 데이터를 list로 표현해서 추려내는 방법
print(arr[:2, :-1])
print(arr[:2, [0, 2]])
#     원하는 열의 데이터를 list로 표현해서 추출하기

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
10
[6]
[[5]]
[[0 1 2]
 [4 5 6]]
[[0 2]
 [4 6]]


In [65]:
# 지금까지 학습한 내용
# 기본적인 indexing, 기본적인 slicing, Boolean indexing, Fancy indexing

In [70]:
# ndarray의 연산

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
arr1 = np.arange(1, 7, 1).reshape(3, 2)
arr2 = np.arange(1, 7, 1).reshape(2, 3)
print(arr1)
print(arr2)

# 연산이 수행되려면, shape이 같아야 한다.
# print(arr + arr1) # 오류
print(arr + arr2) # 오류 아님

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]


In [79]:
# Broadcasting
arr = np.array([1, 2, 3, 4, 5])
print(arr) # 1차원 ndarray
print(arr + 3) # 오류 아님
#     위 코드를 실행하면, 3 이 [3, 3, 3, 3, 3]으로 자동으로 변경되어 연산이 수행되기 때문
#     이를 broadcasting이라고 한다.

# 예시
arr = np.arange(0, 6, 1).reshape(2, 3)
print(arr + 3)
arr1 = np.array([1, 2, 3])
print(arr)
print(arr1)
print(arr + arr1)

[1 2 3 4 5]
[4 5 6 7 8]
[[3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]]
[1 2 3]
[[1 3 5]
 [4 6 8]]


In [81]:
# 행렬 곱연산

arr1 = np.array([[1, 2], [3, 4], [5, 6]])
print(arr1)
arr2 = np.array([[1, 2], [3, 4]])
print(arr2)

# 행렬곱
print(np.dot(arr1, arr2))

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]]
[[ 7 10]
 [15 22]
 [23 34]]


In [94]:
# 집계함수와 축

# 집계함수
#     집계함수를 사용하는 것이 로직으로 처리하는 것보다 처리속도가 훨씬 빠르다.
arr = np.arange(1, 6, 1)
print(arr)
print(arr.sum()) # 출력 : 15
print(arr.mean()) # 출력 : 3.0
print(arr.max()) # 출력 : 5
print(arr.argmax()) # 출력 : 4
#     argmax() : 가장 큰 값을 가지는 숫자의 인덱스

# 축. axis
# 1차원 ndarray는 축 1개
#     축을 숫자로 표현하기.
print(arr.sum(axis = 0)) # 출력 : 15

arr = np.arange(1, 7, 1).reshape(2, 3)
print(arr)
print(arr.sum()) # 출력 : 21
#     축에 상관없이 더하기
# 2차원 ndarray는 축 2개
#     행 방향(행이 증가하는 방향) => 0, 열 방향(열이 증가하는 방향) => 1
print(arr.sum(axis = 0)) # 출력 : [5 7 9]
print(arr.sum(axis = 1)) # 출력 : [ 6 15]


[1 2 3 4 5]
15
3.0
5
4
15
[[1 2 3]
 [4 5 6]]
21
[5 7 9]
[ 6 15]


In [103]:
# 문제
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])
# 10보다 큰 값들의 합은 얼마인가?
print(arr[arr > 10].sum())

81
