## 연습문제
### Titanic - Machine Learning from Disaster

In [20]:
# Module 불러오기
import numpy as np
import pandas as pd

# Raw Data Loading
train = pd.read_csv('./data/titanic/train.csv')
display(train.head())
# Survived
#     0 : 사망, 1 : 
# Pclass
#     객실 등급
# Name
#     이름
# Sex
#     성별
# SibSp
#     형제, 배우자 인원수
# Parch
#     부모, 자식 인원수
# Cabin
#     캐비넷 번호
# Embarked
#     승선지

# 종속변수 설정
#     생존여부. Survived
#     나머지는 모두 독립변수

# 독립변수 중 종속변수에 영향을 미치지 않는 것들 찾아서 제거하기
#     원래는 상관대수 같은 것들을 조사해야 한다. 실제로 수학 식이 있다.
#     PassengerId, Pclass, Name(의미를 더 찾을 수는 있으나 우리는 제외시키자), Ticket, Cabin
#     Fare같은 경우, Pclass와 비슷하게 가기 때문에 제외시키자.
train.drop(['PassengerId', 'Name', 'Ticket', 'Fare', 'Cabin'], axis=1, inplace=True)
#     우리는 지금 열을 지울 거야. '행 과 열'. '0 과 1'. 열이 1 이라고 외워도 된다.
display(train.head())

# 머신러닝에 글자는 넣을 수 없다.
#     0 : male, 1 : female
my_map = {'male' : 0, 'female': 1} # dictionary
train['Sex'] = train['Sex'].map(my_map)
# map()
#     원본 시리즈에서, () 안의 딕셔너리 데이터에 맞춰서 Series의 값을 바꿔준다.
display(train.head())

# 가족 데이터 처리
train['Family'] = train['SibSp'] + train['Parch']
train.drop(['SibSp', 'Parch'], axis=1, inplace=True)
display(train.head())

# 결측치 처리
display(train.info())
# Age
#     NaN이 꽤 있다.
# Embarked
#     NaN이 2개 있다.
# 이번엔 지우지 않고, NaN에 값을 채워보자.

# 결측치 처리 - Embarked
# 가장 빈도가 많은 걸 찾아서 대체하자.
train['Embarked'] = train['Embarked'].fillna('Q') # NaN 값을 대체하기
display(train.info())
my_embarked_map = { 'C': 0, 'S': 1, 'Q': 2 }
train['Embarked'] = train['Embarked'].map(my_embarked_map)
display(train.head())

# 결측치 처리 - Age
# 삭제하면 데이터가 너무 적어진다. 다른 값으로 대체하자.
# 대표값 지정
#     평균
train['Age'] = train['Age'].fillna(train['Age'].mean())
display(train.info())

# Age만 범위가 크다.
# 정규화를 해도 된다. 그런데 정규화를 하면, 나중에 역정규화를 해야한다.
# 구간값으로 사용하는 게 더 좋을 것 같다.
#

# 8살 이하만 추출
train.loc[train['Age'] < 8, 'Age'] = 0
train.loc[(train['Age'] >= 8) & (train['Age'] < 20), 'Age'] = 1
train.loc[(train['Age'] >= 20) & (train['Age'] < 65), 'Age'] = 2
train.loc[train['Age'] >= 65, 'Age'] = 3

display(train.head())


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

Survived  Pclass     Sex   Age  SibSp  Parch Embarked
0         0       3    male  22.0      1      0        S
1         1       1  female  38.0      1      0        C
2         1       3  female  26.0      0      0        S
3         1       1  female  35.0      1      0        S
4         0       3    male  35.0      0      0        S

Survived  Pclass  Sex   Age  SibSp  Parch Embarked
0         0       3    0  22.0      1      0        S
1         1       1    1  38.0      1      0        C
2         1       3    1  26.0      0      0        S
3         1       1    1  35.0      1      0        S
4         0       3    0  35.0      0      0        S

Survived  Pclass  Sex   Age Embarked  Family
0         0       3    0  22.0        S       1
1         1       1    1  38.0        C       1
2         1       3    1  26.0        S       0
3         1       1    1  35.0        S       1
4         0       3    0  35.0        S       0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    int64  
 3   Age       714 non-null    float64
 4   Embarked  889 non-null    object 
 5   Family    891 non-null    int64  
dtypes: float64(1), int64(4), object(1)
memory usage: 41.9+ KB


None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    int64  
 3   Age       714 non-null    float64
 4   Embarked  891 non-null    object 
 5   Family    891 non-null    int64  
dtypes: float64(1), int64(4), object(1)
memory usage: 41.9+ KB


None

Survived  Pclass  Sex   Age  Embarked  Family
0         0       3    0  22.0         1       1
1         1       1    1  38.0         0       1
2         1       3    1  26.0         1       0
3         1       1    1  35.0         1       1
4         0       3    0  35.0         1       0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    int64  
 3   Age       891 non-null    float64
 4   Embarked  891 non-null    int64  
 5   Family    891 non-null    int64  
dtypes: float64(1), int64(5)
memory usage: 41.9 KB


None

Survived  Pclass  Sex  Age  Embarked  Family
0         0       3    0  2.0         1       1
1         1       1    1  2.0         0       1
2         1       3    1  2.0         1       0
3         1       1    1  2.0         1       1
4         0       3    0  2.0         1       0

In [23]:
# Training Data Set

x_data = train.drop('Survived', axis=1, inplace=False).values
print(x_data)
t_data = train['Survived'].values.reshape(-1,1)


[[3. 0. 2. 1. 1.]
 [1. 1. 2. 0. 1.]
 [3. 1. 2. 1. 0.]
 ...
 [3. 1. 2. 1. 3.]
 [1. 0. 2. 0. 0.]
 [3. 0. 2. 2. 0.]]


In [24]:
# Model 만들기

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dense
from tensorflow.keras.optimizers import Adam

# Model
model = Sequential()

# Model에 Layer 추가
# 독립변수의 개수만큼 input layer의 동그라미가 있어야 한다.
# 지금 독립변수 5개니까 동그라미 5개 사용
model.add(Flatten(input_shape=(5,)))
model.add(Dense(1, activation='sigmoid'))

# Model 설정
model.compile(optimizer=Adam(learning_rate=1e-2), loss='binary_crossentropy',
             metrics=['accuracy'])

# Model 학습
model.fit(x_data, t_data, epochs=500,
          validation_split=0.2,
          verbose=1)
# 출력
#     Epoch 500/500
#     23/23 [==============================] - 0s 3ms/step - loss: 0.4566 - accuracy: 0.8034 - val_loss: 0.3935 - val_accuracy: 0.8156
#     <keras.callbacks.History at 0x24ffd50d280>
# val_accuracy 값이 가장 중요한데, 0.82 정도를 벗어나지 못한다.
#     데이터의 개수가 적어서 이 정도가 한계인 것


Epoch 1/500
23/23 [==============================] - 1s 12ms/step - loss: 0.8030 - accuracy: 0.5716 - val_loss: 0.7421 - val_accuracy: 0.6536
Epoch 2/500
23/23 [==============================] - 0s 2ms/step - loss: 0.7118 - accuracy: 0.6348 - val_loss: 0.6619 - val_accuracy: 0.7207
Epoch 3/500
23/23 [==============================] - 0s 2ms/step - loss: 0.6411 - accuracy: 0.6826 - val_loss: 0.5928 - val_accuracy: 0.7486
Epoch 4/500
23/23 [==============================] - 0s 3ms/step - loss: 0.5877 - accuracy: 0.7205 - val_loss: 0.5433 - val_accuracy: 0.7877
Epoch 5/500
23/23 [==============================] - 0s 3ms/step - loss: 0.5529 - accuracy: 0.7444 - val_loss: 0.5114 - val_accuracy: 0.7933
Epoch 6/500
23/23 [==============================] - 0s 3ms/step - loss: 0.5326 - accuracy: 0.7669 - val_loss: 0.4944 - val_accuracy: 0.8268
Epoch 7/500
23/23 [==============================] - 0s 2ms/step - loss: 0.5182 - accuracy: 0.7669 - val_loss: 0.4799 - val_accuracy: 0.8268
Epoch 8/500


Epoch 59/500
23/23 [==============================] - 0s 3ms/step - loss: 0.4607 - accuracy: 0.7978 - val_loss: 0.4095 - val_accuracy: 0.8212
Epoch 60/500
23/23 [==============================] - 0s 3ms/step - loss: 0.4600 - accuracy: 0.7992 - val_loss: 0.4117 - val_accuracy: 0.8212
Epoch 61/500
23/23 [==============================] - 0s 3ms/step - loss: 0.4601 - accuracy: 0.7992 - val_loss: 0.4107 - val_accuracy: 0.8212
Epoch 62/500
23/23 [==============================] - 0s 3ms/step - loss: 0.4613 - accuracy: 0.7992 - val_loss: 0.4103 - val_accuracy: 0.8212
Epoch 63/500
23/23 [==============================] - 0s 2ms/step - loss: 0.4605 - accuracy: 0.7992 - val_loss: 0.4089 - val_accuracy: 0.8212
Epoch 64/500
23/23 [==============================] - 0s 3ms/step - loss: 0.4587 - accuracy: 0.8006 - val_loss: 0.4102 - val_accuracy: 0.8212
Epoch 65/500
23/23 [==============================] - 0s 3ms/step - loss: 0.4598 - accuracy: 0.7978 - val_loss: 0.4078 - val_accuracy: 0.8212
Epoch 

23/23 [==============================] - 0s 3ms/step - loss: 0.4578 - accuracy: 0.8006 - val_loss: 0.3996 - val_accuracy: 0.8212
Epoch 117/500
23/23 [==============================] - 0s 3ms/step - loss: 0.4574 - accuracy: 0.8006 - val_loss: 0.3993 - val_accuracy: 0.8156
Epoch 118/500
23/23 [==============================] - 0s 3ms/step - loss: 0.4562 - accuracy: 0.7992 - val_loss: 0.4018 - val_accuracy: 0.8212
Epoch 119/500
23/23 [==============================] - 0s 3ms/step - loss: 0.4568 - accuracy: 0.7992 - val_loss: 0.3990 - val_accuracy: 0.8212
Epoch 120/500
23/23 [==============================] - 0s 3ms/step - loss: 0.4573 - accuracy: 0.8006 - val_loss: 0.4020 - val_accuracy: 0.8212
Epoch 121/500
23/23 [==============================] - 0s 3ms/step - loss: 0.4580 - accuracy: 0.8020 - val_loss: 0.3993 - val_accuracy: 0.8156
Epoch 122/500
23/23 [==============================] - 0s 3ms/step - loss: 0.4569 - accuracy: 0.8020 - val_loss: 0.3993 - val_accuracy: 0.8156
Epoch 123/500

23/23 [==============================] - 0s 3ms/step - loss: 0.4567 - accuracy: 0.8020 - val_loss: 0.3959 - val_accuracy: 0.8156
Epoch 174/500
23/23 [==============================] - 0s 3ms/step - loss: 0.4566 - accuracy: 0.8020 - val_loss: 0.3957 - val_accuracy: 0.8156
Epoch 175/500
23/23 [==============================] - 0s 3ms/step - loss: 0.4565 - accuracy: 0.8020 - val_loss: 0.3959 - val_accuracy: 0.8156
Epoch 176/500
23/23 [==============================] - 0s 3ms/step - loss: 0.4568 - accuracy: 0.8006 - val_loss: 0.3950 - val_accuracy: 0.8156
Epoch 177/500
23/23 [==============================] - 0s 3ms/step - loss: 0.4570 - accuracy: 0.8006 - val_loss: 0.3966 - val_accuracy: 0.8156
Epoch 178/500
23/23 [==============================] - 0s 3ms/step - loss: 0.4576 - accuracy: 0.7949 - val_loss: 0.3951 - val_accuracy: 0.8212
Epoch 179/500
23/23 [==============================] - 0s 3ms/step - loss: 0.4588 - accuracy: 0.8034 - val_loss: 0.3985 - val_accuracy: 0.8156
Epoch 180/500

23/23 [==============================] - 0s 3ms/step - loss: 0.4563 - accuracy: 0.8020 - val_loss: 0.3959 - val_accuracy: 0.8156
Epoch 231/500
23/23 [==============================] - 0s 3ms/step - loss: 0.4559 - accuracy: 0.8020 - val_loss: 0.3932 - val_accuracy: 0.8156
Epoch 232/500
23/23 [==============================] - 0s 3ms/step - loss: 0.4565 - accuracy: 0.8006 - val_loss: 0.3941 - val_accuracy: 0.8156
Epoch 233/500
23/23 [==============================] - 0s 3ms/step - loss: 0.4560 - accuracy: 0.8020 - val_loss: 0.3927 - val_accuracy: 0.8156
Epoch 234/500
23/23 [==============================] - 0s 3ms/step - loss: 0.4564 - accuracy: 0.8034 - val_loss: 0.3955 - val_accuracy: 0.8156
Epoch 235/500
23/23 [==============================] - 0s 3ms/step - loss: 0.4560 - accuracy: 0.8006 - val_loss: 0.3946 - val_accuracy: 0.8156
Epoch 236/500
23/23 [==============================] - 0s 3ms/step - loss: 0.4568 - accuracy: 0.8006 - val_loss: 0.3932 - val_accuracy: 0.8156
Epoch 237/500

23/23 [==============================] - 0s 3ms/step - loss: 0.4568 - accuracy: 0.8006 - val_loss: 0.3920 - val_accuracy: 0.8212
Epoch 288/500
23/23 [==============================] - 0s 3ms/step - loss: 0.4563 - accuracy: 0.8034 - val_loss: 0.3949 - val_accuracy: 0.8156
Epoch 289/500
23/23 [==============================] - 0s 3ms/step - loss: 0.4568 - accuracy: 0.7992 - val_loss: 0.3929 - val_accuracy: 0.8212
Epoch 290/500
23/23 [==============================] - 0s 3ms/step - loss: 0.4561 - accuracy: 0.8006 - val_loss: 0.3926 - val_accuracy: 0.8156
Epoch 291/500
23/23 [==============================] - 0s 3ms/step - loss: 0.4561 - accuracy: 0.8020 - val_loss: 0.3931 - val_accuracy: 0.8156
Epoch 292/500
23/23 [==============================] - 0s 3ms/step - loss: 0.4563 - accuracy: 0.8020 - val_loss: 0.3929 - val_accuracy: 0.8156
Epoch 293/500
23/23 [==============================] - 0s 3ms/step - loss: 0.4575 - accuracy: 0.7992 - val_loss: 0.3920 - val_accuracy: 0.8156
Epoch 294/500

23/23 [==============================] - 0s 3ms/step - loss: 0.4575 - accuracy: 0.8020 - val_loss: 0.3941 - val_accuracy: 0.8156
Epoch 345/500
23/23 [==============================] - 0s 3ms/step - loss: 0.4573 - accuracy: 0.7992 - val_loss: 0.3928 - val_accuracy: 0.8212
Epoch 346/500
23/23 [==============================] - 0s 3ms/step - loss: 0.4565 - accuracy: 0.7992 - val_loss: 0.3941 - val_accuracy: 0.8156
Epoch 347/500
23/23 [==============================] - 0s 3ms/step - loss: 0.4577 - accuracy: 0.8006 - val_loss: 0.3943 - val_accuracy: 0.8212
Epoch 348/500
23/23 [==============================] - 0s 3ms/step - loss: 0.4570 - accuracy: 0.7978 - val_loss: 0.3935 - val_accuracy: 0.8156
Epoch 349/500
23/23 [==============================] - 0s 3ms/step - loss: 0.4572 - accuracy: 0.8006 - val_loss: 0.3929 - val_accuracy: 0.8212
Epoch 350/500
23/23 [==============================] - 0s 3ms/step - loss: 0.4583 - accuracy: 0.8006 - val_loss: 0.3921 - val_accuracy: 0.8212
Epoch 351/500

23/23 [==============================] - 0s 3ms/step - loss: 0.4563 - accuracy: 0.8020 - val_loss: 0.3927 - val_accuracy: 0.8212
Epoch 402/500
23/23 [==============================] - 0s 3ms/step - loss: 0.4562 - accuracy: 0.8006 - val_loss: 0.3928 - val_accuracy: 0.8156
Epoch 403/500
23/23 [==============================] - 0s 3ms/step - loss: 0.4568 - accuracy: 0.8006 - val_loss: 0.3943 - val_accuracy: 0.8156
Epoch 404/500
23/23 [==============================] - 0s 3ms/step - loss: 0.4568 - accuracy: 0.8020 - val_loss: 0.3945 - val_accuracy: 0.8156
Epoch 405/500
23/23 [==============================] - 0s 3ms/step - loss: 0.4561 - accuracy: 0.8034 - val_loss: 0.3933 - val_accuracy: 0.8212
Epoch 406/500
23/23 [==============================] - 0s 3ms/step - loss: 0.4575 - accuracy: 0.8006 - val_loss: 0.3958 - val_accuracy: 0.8156
Epoch 407/500
23/23 [==============================] - 0s 3ms/step - loss: 0.4561 - accuracy: 0.8020 - val_loss: 0.3911 - val_accuracy: 0.8212
Epoch 408/500

23/23 [==============================] - 0s 3ms/step - loss: 0.4569 - accuracy: 0.8006 - val_loss: 0.3935 - val_accuracy: 0.8156
Epoch 459/500
23/23 [==============================] - 0s 3ms/step - loss: 0.4561 - accuracy: 0.8034 - val_loss: 0.3933 - val_accuracy: 0.8212
Epoch 460/500
23/23 [==============================] - 0s 3ms/step - loss: 0.4592 - accuracy: 0.7921 - val_loss: 0.3920 - val_accuracy: 0.8156
Epoch 461/500
23/23 [==============================] - 0s 3ms/step - loss: 0.4569 - accuracy: 0.8006 - val_loss: 0.3939 - val_accuracy: 0.8156
Epoch 462/500
23/23 [==============================] - 0s 2ms/step - loss: 0.4574 - accuracy: 0.7978 - val_loss: 0.3922 - val_accuracy: 0.8156
Epoch 463/500
23/23 [==============================] - 0s 3ms/step - loss: 0.4567 - accuracy: 0.8020 - val_loss: 0.3930 - val_accuracy: 0.8156
Epoch 464/500
23/23 [==============================] - 0s 3ms/step - loss: 0.4565 - accuracy: 0.8006 - val_loss: 0.3919 - val_accuracy: 0.8212
Epoch 465/500

In [ ]:
# 예측하기

# Model 이 완성됐으니, Kaggle이 제공해준 test.csv 파일을 이용하여 prediction을 해야 한다.
# 먼저 test.csv를 읽어들여서 이 데이터를 다시 변형시켜야 한다.
#     machine learning model에 입력으로 넣어야 하기 때문
# 결과가 나오면 이쁘게 결과파일을 만들어서 Kaggle에 제출해서 우리 모델의 정확도를 측정받으면 된다.
